export type EditableSection = 'packages' | 'offers';
export const defaultEditableContent = [
  { section:'packages', key:'package-1', sort_order:1, data:{ image_url:'/images/package-silver.jpeg', name_ar:'الباقة الفضية', name_en:'Silver Package', label_ar:'زهرة الفرسان • المدينة الجديد', label_en:'Zahra Al-Fursan • Al Madinah Al Jadeed', price:'761', price_prefix_ar:'ابتداءً من', price_prefix_en:'Starting from', price_label_ar:'ريال سعودي للفرد', price_label_en:'Saudi riyals per person', description_ar:'باقة متوازنة تجمع بين القرب من الحرم والخدمات الأساسية المتكاملة.', description_en:'A balanced package combining proximity to the Haram with complete essential services.', features_ar:['9 ليالٍ في مكة — زهرة الفرسان، أجياد','3 ليالٍ في المدينة — المدينة الجديد','التأشيرة والنقل والفنادق والإعاشة مشمولة'], features_en:['9 nights in Makkah — Zahra Al-Fursan, Ajyad','3 nights in Madinah — Al Madinah Al Jadeed','Visa, transportation, hotels, and catering included'], cta_ar:'اختيار الباقة الفضية', cta_en:'Choose Silver Package', featured:false } },
  { section:'packages', key:'package-2', sort_order:2, data:{ image_url:'/images/package-gold.jpeg', name_ar:'الباقة الذهبية', name_en:'Gold Package', label_ar:'إيلاف الخير • سلسبيل الفضي', label_en:'Elaf Al-Khair • Salsabeel Al-Fadhi', price:'953', price_prefix_ar:'ابتداءً من', price_prefix_en:'Starting from', price_label_ar:'ريال سعودي للفرد', price_label_en:'Saudi riyals per person', description_ar:'إقامة عملية ومتكاملة لمدة 12 ليلة بين مكة المكرمة والمدينة المنورة.', description_en:'A practical, complete 12-night stay between Makkah and Madinah.', features_ar:['9 ليالٍ في مكة — إيلاف الخير، أجياد','3 ليالٍ في المدينة — سلسبيل الفضي','التأشيرة والنقل والفنادق والإعاشة مشمولة'], features_en:['9 nights in Makkah — Elaf Al-Khair, Ajyad','3 nights in Madinah — Salsabeel Al-Fadhi','Visa, transportation, hotels, and catering included'], cta_ar:'اختيار الباقة الذهبية', cta_en:'Choose Gold Package', featured:false } },
  { section:'packages', key:'package-3', sort_order:3, data:{ image_url:'/images/package-diamond.jpeg', name_ar:'الباقة الماسية', name_en:'Diamond Package', label_ar:'مكارم الهجرة • طابة السلام', label_en:'Makarem Al-Hijra • Taba Al Salam', price:'833', price_prefix_ar:'ابتداءً من', price_prefix_en:'Starting from', price_label_ar:'ريال سعودي للفرد', price_label_en:'Saudi riyals per person', description_ar:'إقامة مريحة في مكة والمدينة مع جميع خدمات الرحلة الأساسية.', description_en:'A comfortable Makkah and Madinah stay with every essential journey service included.', features_ar:['9 ليالٍ في مكة — مكارم الهجرة، المسفلة','3 ليالٍ في المدينة — طابة السلام','التأشيرة والنقل والفنادق والإعاشة مشمولة'], features_en:['9 nights in Makkah — Makarem Al-Hijra, Al-Misfalah','3 nights in Madinah — Taba Al Salam','Visa, transportation, hotels, and catering included'], cta_ar:'اختيار الباقة الماسية', cta_en:'Choose Diamond Package', featured:false } },
  { section:'packages', key:'package-4', sort_order:4, data:{ image_url:'/images/package-platinum.jpeg', name_ar:'الباقة البلاتينية', name_en:'Platinum Package', label_ar:'الأقرب إلى الحرم', label_en:'Closest to the Haram', price:'1,761', price_prefix_ar:'ابتداءً من', price_prefix_en:'Starting from', price_label_ar:'ريال سعودي للفرد', price_label_en:'Saudi riyals per person', description_ar:'إقامة مميزة بجوار أبراج البيت مع سهولة الوصول إلى الحرم المكي.', description_en:'A distinguished stay beside Abraj Al Bait with easy access to the Grand Mosque.', features_ar:['9 ليالٍ في مكة — إيلاف كندة، 100 م من الحرم','3 ليالٍ في المدينة — المنا كريم','التأشيرة والنقل والفنادق والإعاشة مشمولة'], features_en:['9 nights in Makkah — Elaf Kinda, 100 m from the Haram','3 nights in Madinah — Al Mana Kareem','Visa, transportation, hotels, and catering included'], cta_ar:'اختيار الباقة البلاتينية', cta_en:'Choose Platinum Package', featured:true } },
  { section:'offers', key:'ramadan', sort_order:1, data:{ image_url:'/images/saudi-atlas.jpg', title_ar:'باقات رمضان', title_en:'Ramadan Packages', text_ar:'عِش تجربة العمرة في أقدس الأوقات. برامج مخصصة لشهر رمضان المبارك بمزايا استثنائية.', text_en:'Experience Umrah in the holiest of months. Exclusive programs designed for the blessed month of Ramadan.' } },
  { section:'offers', key:'december', sort_order:2, data:{ image_url:'/images/saudi-atlas.jpg', title_ar:'عروض ديسمبر', title_en:'December Offers', text_ar:'اختم عامك برحلة عمرة لا تُنسى. باقات موسم نهاية العام بأسعار مميزة.', text_en:'End your year with a spiritual journey to remember. Year-end season packages at special rates.' } },
  { section:'offers', key:'national-day', sort_order:3, data:{ image_url:'/images/saudi-atlas.jpg', title_ar:'اليوم الوطني', title_en:'National Day', text_ar:'عروض خاصة بمناسبة اليوم الوطني.', text_en:'Special offers for the Saudi National Day.' } },
] as const;
